language: node_js
node_js:
  - 10.13.0
install:
  - npm install
script:
  - npm run test
branches:
  only:
    - main
    - dev
deploy:
  provider: heroku
  api_key:
    secure: sGwCwuMdwfPGAgDl494PIfEocmZluHlJiRkB2xMmLNZTVVvBH/QINvdIlS/Fq6pB/QUmEdDjTZ3CF/gGDsG5FiQkMo/7Bl9Ej+H+h8N72yBQVN1ZJ6Ey61HF5erhuczq/zmhXDPkEXXzTAvaB6lR2BeCS68oZBPT3J+Qsp4P7P0fSvARlz64g+Bg0Uw5WaW+K7lYxDnIZFAzi2l2E6rym3dyNcnIMvlItwsl0Sm+yabnJdOv9ICA3euasWxzBLosJasAjP7LOvoAqf2pFfTFxAdixpasoxhlbdmOAgbTBTgGi0BACNZ7MGC22k/d0c0qKXVPO42J4P+li58snsYDwYCRQXq21gP6QzN03+R8bFB2ufxRRzSxCCGWJ0eGaZc/dwsYDFQSkEQZLI2EdPUP+zwIggjQ/+h+UF4r8Or64+p8F19TDRZNXL1d3rBP4E+IH53ytO06/nFW9ADPPETjodU48weP1mDEf371ZfXY1dXDN31yIlgFo604ySeBVlWs9SNQtHrUIyegmuIj4DAovMXuVk8StvarrUzfIM+J15rVL9K4sf7WKPasdAE1eIkjzKW0VXA3t4re9CnxGW9MzOW2oOphmfOzrp0w3L5cnri8zIC2jCUOPHsgnUJj2BHLQGbZGb2NjRXO5fcfMFfEf4lOA48gSaCbGvhSLSXelAo=
  app:
    master: travis-demo-prod
    dev: travis-demo-staging